# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41e9bcd3adacdeb12b8dc29d2e71136f"
name = "Devoluciones"
handle = "reverse-logistics"
application_url = "https://amy-costume-blog-fed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-978c50de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://amy-costume-blog-fed.trycloudflare.com/auth/callback",
  "https://amy-costume-blog-fed.trycloudflare.com/auth/shopify/callback",
  "https://amy-costume-blog-fed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
