# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1dd4dfd50b39902e7542119ddcccd275"
name = "Reverse Logistics"
handle = "reverse-logistics-1"
application_url = "https://well-expenditure-social-http.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-978c50de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://well-expenditure-social-http.trycloudflare.com/auth/callback",
  "https://well-expenditure-social-http.trycloudflare.com/auth/shopify/callback",
  "https://well-expenditure-social-http.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
