# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1dd4dfd50b39902e7542119ddcccd275"
name = "Reverse"
handle = "reverse"
application_url = "https://reverse-logistics-aged-grass-1765.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-978c50de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://reverse-logistics-aged-grass-1765.fly.dev/auth/callback",
  "https://reverse-logistics-aged-grass-1765.fly.dev/auth/shopify/callback",
  "https://reverse-logistics-aged-grass-1765.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://reverse-logistics-aged-grass-1765.fly.dev/app/proxy"
subpath = "store-return"
prefix = "apps"

[pos]
embedded = false
