# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "41e9bcd3adacdeb12b8dc29d2e71136f"
name = "Reverse"
handle = "reverse"
application_url = "https://launches-todd-circulation-verde.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-978c50de.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://launches-todd-circulation-verde.trycloudflare.com/auth/callback",
  "https://launches-todd-circulation-verde.trycloudflare.com/auth/shopify/callback",
  "https://launches-todd-circulation-verde.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[app_proxy]
url = "https://bio-appendix-wichita-enough.trycloudflare.com/"
subpath = "store-return"
prefix = "apps"

[pos]
embedded = false
