-- CreateTable
CREATE TABLE `SESSION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `shop` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `isOnline` BOOLEAN NOT NULL DEFAULT false,
    `scope` VARCHAR(191) NULL,
    `expires` DATETIME(3) NULL,
    `accessToken` VARCHAR(191) NOT NULL,
    `userId` BIGINT NULL,
    `firstName` VARCHAR(191) NULL,
    `lastName` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `accountOwner` BOOLEAN NOT NULL DEFAULT false,
    `locale` VARCHAR(191) NULL,
    `collaborator` BOOLEAN NULL DEFAULT false,
    `emailVerified` BOOLEAN NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DEVOLUTION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` VARCHAR(191) NOT NULL,
    `mainReason` VARCHAR(191) NOT NULL,
    `sucursal` VARCHAR(191) NOT NULL,
    `explanation` VARCHAR(191) NOT NULL,
    `ticketNumber` INTEGER NOT NULL,
    `clientNumber` INTEGER NOT NULL,
    `orderNumber` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `returnmentLabel` VARCHAR(191) NOT NULL,
    `dateProductArrive` DATETIME(3) NOT NULL,
    `shippingPayment` BOOLEAN NOT NULL DEFAULT false,
    `requiresLabel` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DEVOLUTION_ITEM` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `devolutionId` INTEGER NOT NULL,
    `sku` VARCHAR(191) NOT NULL,
    `quantity` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DEVOLUTION_IMAGE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `devolutionId` INTEGER NOT NULL,
    `image` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESOLUTION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `comentarios` VARCHAR(191) NOT NULL,
    `ndc` VARCHAR(191) NOT NULL,
    `devolutionId` INTEGER NOT NULL,

    UNIQUE INDEX `RESOLUTION_devolutionId_key`(`devolutionId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RESOLUTION_IMAGE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `resolutionId` INTEGER NOT NULL,
    `image` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DEVOLUTION_ITEM` ADD CONSTRAINT `DEVOLUTION_ITEM_devolutionId_fkey` FOREIGN KEY (`devolutionId`) REFERENCES `DEVOLUTION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DEVOLUTION_IMAGE` ADD CONSTRAINT `DEVOLUTION_IMAGE_devolutionId_fkey` FOREIGN KEY (`devolutionId`) REFERENCES `DEVOLUTION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESOLUTION` ADD CONSTRAINT `RESOLUTION_devolutionId_fkey` FOREIGN KEY (`devolutionId`) REFERENCES `DEVOLUTION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `RESOLUTION_IMAGE` ADD CONSTRAINT `RESOLUTION_IMAGE_resolutionId_fkey` FOREIGN KEY (`resolutionId`) REFERENCES `RESOLUTION`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
